### ISSUE TITLE
SIGSEGV: segmentation violation

### ISSUE THREAD

**Issue by syphernl** [kitos9112/terragrunt-gitlab-cicd-config#129]
Running this tool (v2.0.1) on my Terragrunt codebase I get the following:

```txt
...
DEBU[0007] Dealing with dependencyPath /app/infra/_envcommon/frontend/ecs-task.hcl 
DEBU[0007] Dealing with dependencyPath /app/infra/production/eu-west-1/ecr-frontend/terragrunt.hcl 
DEBU[0007] Dealing with dependencyPath /app/infra/_envcommon/frontend/ecr.hcl 
DEBU[0007] Dealing with dependencyPath /app/infra/production/eu-west-1/cloudfront-oai/terragrunt.hcl 
DEBU[0007] Dealing with dependencyPath /app/infra/production/eu-west-1/cloudfront-policies/terragrunt.hcl 
DEBU[0007] Dealing with dependencyPath /app/infra/_envcommon/cloudfront_policies.hcl 
DEBU[0007] Dealing with dependencyPath /app/infra/terraform.tfvars 
INFO[0007] Collected dependencies for /app/infra/production/eu-west-1/cloudfront/terragrunt.hcl 
ERRO[0007] open : no such file or directory             
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x53f2cc]

goroutine 1 [running]:
text/template.errRecover(0xc0007f37f8)
	/opt/homebrew/Cellar/go/1.19.5/libexec/src/text/template/exec.go:164 +0x165
panic({0x12c9e60, 0x2168d70})
	/opt/homebrew/Cellar/go/1.19.5/libexec/src/runtime/panic.go:884 +0x212
text/template.(*Template).execute(0x0, {0x180b840?, 0xc000308028?}, {0x1368500?, 0xc0006d1b90?})
	/opt/homebrew/Cellar/go/1.19.5/libexec/src/text/template/exec.go:215 +0x22c
text/template.(*Template).Execute(...)
	/opt/homebrew/Cellar/go/1.19.5/libexec/src/text/template/exec.go:201
github.com/kitos9112/terragrunt-gitlab-cicd-config/cmd.main(0x217c060?, {0x146b451?, 0x2?, 0x2?})
	/Users/marcos.soutullo/projects/home/github.com/kitos9112/terragrunt-gitlab-cicd-config/cmd/generate.go:551 +0x91c
github.com/spf13/cobra.(*Command).execute(0x217c060, {0xc00009aa60, 0x2, 0x2})
	/Users/marcos.soutullo/Go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x217c340)
	/Users/marcos.soutullo/Go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/marcos.soutullo/Go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/kitos9112/terragrunt-gitlab-cicd-config/cmd.Execute({0x146bf8b?, 0xc0000061a0?})
	/Users/marcos.soutullo/projects/home/github.com/kitos9112/terragrunt-gitlab-cicd-config/cmd/root.go:26 +0x51
main.main()
	/Users/marcos.soutullo/projects/home/github.com/kitos9112/terragrunt-gitlab-cicd-config/main.go:11 +0x27
```

Command: 
```shell
terragrunt-gitlab-cicd-config generate  --verbosity trace
```

I have tried to run this on two codebases where we use terragrunt-atlantis-config, but both are giving the same output.

**Comment by kitos9112** [comment]
Hello @syphernl!

Thanks for trying it out. I'm not actively maintaining it but happy to give you a hand.

I suspect you have a relative path in one of those HCL files that this Go app is not able to safely open - What's the current working directory from where you're running the app?

**Comment by gmspinheiro** [comment]
I believe the issue is that you don't have supplied template input file. Use the --input arg or create the template file in the same directory where you run the command. Use the test/inputs/.gitlab-ci.yml.tpl as your base.

**Comment by syphernl** [comment]
> I believe the issue is that you don't have supplied template input file. Use the --input arg or create the template file in the same directory where you run the command. Use the test/inputs/.gitlab-ci.yml.tpl as your base.

You are correct. After copying `.gitlab-ci.yml.tpl` to the project and providing it to this tool with `--input .gitlab-ci.yml.tpl` it generated a `.gitlab-ci.yml` without any issues.
